artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Rupanshu-Kapoor/Chicken-Disease-Classification/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/Chicken-fecal-images.zip
  unzip_dir: artifacts/data_ingestion/Chicken-fecal-images



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras
  